import localFont from 'next/font/local';
import './globals.css';
import NavBar from '@/components/NavBar';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

const poppins = localFont({
  src: './fonts/PoppinsVF.ttf',
  variable: '--font-poppins',
  weight: '100 900',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} ${geistMono.variable} antialiased min-h-screen flex flex-col bg-slate-100 text-slate-900 bg-pattern`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
